import { Inter } from "next/font/google";
import "./globals.css";
import GoogleAnalytics from "./components/GoogleAnalytics";
import CookieBanner from "./components/cookiebanner";
import { Suspense } from "react";
import ProgressBarProvider from "./components/ProgressBarProvider";
import { GoogleTagManager } from '@next/third-parties/google'
import Head from "next/head";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <script
          id="gtm-script"
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-P9QGV5FL');`,
          }}
        />
      </Head>
      <body className={inter.className}>
        <Suspense fallback={<div>Loading...</div>}>
          <GoogleTagManager gtmId="GTM-P9QGV5FL" />
          <GoogleAnalytics />
        </Suspense>
          <ProgressBarProvider>{children}</ProgressBarProvider>
        <CookieBanner />
      </body>
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-P9QGV5FL"
        height="0" width="0" style={{ display: 'none', visibility: 'hidden' }}></iframe></noscript>
    </html>
  );
}
